"""chat attachments and recurring tasks

Revision ID: 02d988665dac
Revises: e17dde181b84
Create Date: 2026-03-02 12:55:07.796462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d988665dac'
down_revision = 'e17dde181b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attachment_mimetype', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('attachment_mimetype')
        batch_op.drop_column('attachment_size')
        batch_op.drop_column('attachment_path')
        batch_op.drop_column('attachment_filename')

    # ### end Alembic commands ###
