"""add recurring tasks

Revision ID: e17dde181b84
Revises: 254506e27044
Create Date: 2026-03-02 12:43:14.700568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17dde181b84'
down_revision = '254506e27044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('assignee_ids', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=True),
    sa.Column('next_due', sa.DateTime(), nullable=True),
    sa.Column('last_generated', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_tasks')
    # ### end Alembic commands ###
